### PR TITLE
chore: Add .github templates

### PR DESCRIPTION
**Pull request by WilcoFiers**
Add .github templates

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [ ] Follows the commit message policy, appropriate for next version
- [ ] Has documentation updated, a DU ticket, or requires no documentation change
- [ ] Includes new tests, or was unnecessary
- [ ] Code is reviewed for security by: << Name here >>

### CODE REVIEW

**Comment by jasonkarns** [comment]
These can also live in `docs/` instead of `.github/` if desired.

**Comment by WilcoFiers** [comment]
@jkodu can you figure out why this PR is failing in CI?

**Comment by jkodu** [comment]
@wilco - 
FYI, issue is with circleci, see - https://github.com/rspec/rspec-core/issues/2451
I will see what fix I can put in place for this. Locally rake: spec ci runs fine.

**Comment by jkodu** [comment]
This PR, handles the same changes. Closing this.

**Pull request closed without merging**
